CREATE DATABASE biblioteca;
GO

USE biblioteca;
GO

CREATE TABLE usuario (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);
GO

CREATE TABLE livro (
    id INT IDENTITY(1,1) PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dtLivro DATETIME2 DEFAULT SYSDATETIME(),
    descricao VARCHAR(255),
    img VARBINARY(MAX)
);
GO
